# Generated by Django 4.1.3 on 2022-11-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(max_length=100)),
            ],
        ),
    ]
