# Generated by Django 4.1.3 on 2022-11-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanager', '0003_employee_jobemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobemployee',
            name='end_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobemployee',
            name='start_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
