# Generated by Django 4.1.3 on 2022-12-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=100)),
                ("job_description", models.CharField(max_length=1000)),
                ("job_location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="job_type",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="job_user",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="worked_hour",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "job_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.job_user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.job_type"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="users",
            field=models.ManyToManyField(
                through="jobs.job_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
