# Generated by Django 4.1.3 on 2023-01-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job_user",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.job_type"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="users",
            field=models.ManyToManyField(
                through="jobs.job_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
